### ISSUE TITLE
Domain Migration Checklist

### ISSUE THREAD

**Issue by Souptik2001** [Souptik2001/Souptik2001.github.io#1]
- [x] Change all the links to relative links.

Optimizations:
- [x] In home page background image is quite large and takes much time to load. Convert to webp and load different sizes based on screen size.
- [x] Fix tastes page.
- [x] Fix about page. ( padding through CSS and not JS ).
- [x] Main fix in about page - Images....better idea to display both the image, but in optimized form.
